In [1]:
import pandas as pd

import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt

In [2]:
data_dr = "./data/"

In [3]:
ds_nat = pd.read_csv(data_dr+"df_fuel_ckan.csv")

In [4]:
ds_nat.head()

,DATETIME,GAS,COAL,NUCLEAR,WIND,HYDRO,IMPORTS,BIOMASS,OTHER,SOLAR,...,IMPORTS_perc,BIOMASS_perc,OTHER_perc,SOLAR_perc,STORAGE_perc,GENERATION_perc,LOW_CARBON_perc,ZERO_CARBON_perc,RENEWABLE_perc,FOSSIL_perc
0,2009-01-01 00:00:00+00,8247.0,15034.0,7099.0,279.0,246.0,2507.0,0.0,0.0,0.0,...,7.5,0.0,0.0,0.0,0.0,100.0,22.8,22.8,1.6,69.7
1,2009-01-01 00:30:00+00,8364.0,15092.0,7088.0,258.0,245.0,2487.0,0.0,0.0,0.0,...,7.4,0.0,0.0,0.0,0.0,100.0,22.6,22.6,1.5,69.9
2,2009-01-01 01:00:00+00,8329.0,15083.0,7074.0,231.0,246.0,2452.0,0.0,0.0,0.0,...,7.3,0.0,0.0,0.0,0.0,100.0,22.6,22.6,1.4,70.1
3,2009-01-01 01:30:00+00,8193.0,15025.0,7064.0,213.0,246.0,2413.0,0.0,0.0,0.0,...,7.3,0.0,0.0,0.0,0.0,100.0,22.7,22.7,1.4,70.0
4,2009-01-01 02:00:00+00,8166.0,14991.0,7052.0,197.0,246.0,2345.0,0.0,0.0,0.0,...,7.1,0.0,0.0,0.0,0.0,100.0,22.7,22.7,1.3,70.2

In [5]:
ds_nat.columns

Index(['DATETIME', 'GAS', 'COAL', 'NUCLEAR', 'WIND', 'HYDRO', 'IMPORTS',
       'BIOMASS', 'OTHER', 'SOLAR', 'STORAGE', 'GENERATION',
       'CARBON_INTENSITY', 'LOW_CARBON', 'ZERO_CARBON', 'RENEWABLE', 'FOSSIL',
       'GAS_perc', 'COAL_perc', 'NUCLEAR_perc', 'WIND_perc', 'HYDRO_perc',
       'IMPORTS_perc', 'BIOMASS_perc', 'OTHER_perc', 'SOLAR_perc',
       'STORAGE_perc', 'GENERATION_perc', 'LOW_CARBON_perc',
       'ZERO_CARBON_perc', 'RENEWABLE_perc', 'FOSSIL_perc'],
      dtype='object')